### ISSUE TITLE
Suggestion: Customisable output

### ISSUE THREAD

**Issue by Slegnor** [cg2121/obs-advanced-timer#1]
Hi, suggestion regarding the format of the timer

Could it be implemented that output of the timer be customisable?

for example:
Currently the timer shows as 00:00:00 (or 00:00:00.0)

Customized format could allow: 00h:00m:00s / 00hr:00min:00sec / 00hrs:00mins:00secs / etc

**Comment by cg2121** [comment]
Resolved with: https://github.com/cg2121/obs-advanced-timer/commit/5829b3887873a0ede6ab504f50a6be462e6582dc
