### ISSUE TITLE
Automatic Scene Switching Option when time is up

### ISSUE THREAD

**Issue by chrisinhim** [cg2121/obs-advanced-timer#10]
When the count down time is reached, it will be good to have an option to switch to the desired scene.

This will help people to start programs/shows on time. 
People can switch to a promo scene or the stage scene.

**Comment by Trouffman** [comment]
You should look at https://github.com/WarmUpTill/SceneSwitcher
Pretty complete so far.

**Comment by cg2121** [comment]
Added with https://github.com/cg2121/obs-advanced-timer/commit/43f93b3a43c48341e13e969881be530003610f9e
