### ISSUE TITLE
Reset timer when stopped causes it to start

### ISSUE THREAD

**Issue by Zhaph** [cg2121/obs-advanced-timer#11]
In both the Countdown and Countup mode, when the timer is stopped, pressing "Reset" causes the timer to start.

I'd like to use this as a stopwatch to showcase speedruns, etc. and it would be great to have the timer starting at `00:00.000` (stopped) and then be able to use the hotkey to start the timer as required.

**Comment by cg2121** [comment]
Fixed with https://github.com/cg2121/obs-advanced-timer/commit/4772824bbb523c0e8efcb3d311a6db5fae2a24e1
