### ISSUE TITLE
Studio mode

### ISSUE THREAD

**Issue by Finch-Tamo** [cg2121/obs-advanced-timer#12]
Before the last update, with studio mode, the countdown reset when i push scene from preview to live but after the last update, the countdown don't reset when i push it from preview to live scene. Possible to fix it ? Because, i think all people use it for countdown want this " option " ;)
Thx for your great work !

**Comment by scostelloquench** [comment]
Its actualy an OBS issue. They If when you are in studio mode you click the settings icon next to the button "Transitions" in the center between preview and program, and disable the first dupicate option it fixes the issue.

**Comment by Finch-Tamo** [comment]
Thx for the tips ! :D It's work !

**Comment by chiyi4488** [comment]
@Finch-Tamo @scostelloquench
Hello! Sorry my English is not very good, which option do I have to disable? I have disabled/enabled all three options and none of them seem to work.
![image](https://user-images.githubusercontent.com/30853081/133917978-d4910f99-3057-4fde-8134-efa4097bb01b.png)
