### ISSUE TITLE
Custom time

### ISSUE THREAD

**Issue by SirHerbert** [cg2121/obs-advanced-timer#15]
Hey, how would I start a countup from let's say 45:00 like a soccer match instead of 00:00?

**Comment by MadDogMayCry0** [comment]
@SirHerbert
openup lua file with text editor
find line 
```
text = string.gsub(text, "%%h", hours)
```
change to
```
text = string.gsub(text, "%%h", hours+1)
```

**Comment by whoibrar** [comment]
Been looking for the same, but the feature is not yet implemented

**Comment by cg2121** [comment]
Added this ability with https://github.com/cg2121/obs-advanced-timer/commit/5c1f4e54f3c7044ecacdc1e505a545958b31f4ac
