### ISSUE TITLE
Resetting to defaults at start in 0.27 rc2

### ISSUE THREAD

**Issue by bruxy70** [cg2121/obs-advanced-timer#16]
I have been trying OBS 0.27 rc2, it looks like it has an issue with the script, it behaves erratically.
It looks like when I hit Start/Stop timer, it will reset the dialogue and load some kind of defaults.
Is this the issue with OBS or with the script?

**Comment by bruxy70** [comment]
I rolled back OBS back to 26.1.1 and there it works again. But it will not in v27 most likely....

**Comment by steven3363** [comment]
Can confirm this behaviour.

**Comment by cg2121** [comment]
I believe this is a bug with undo/redo in OBS 27 messing with properties with scripts.

Fixed with: https://github.com/obsproject/obs-studio/commit/cec8e246303dd1db0adf7ca3d52604cedcdea182
Should be fixed in the next OBS release.
