### ISSUE TITLE
Feature Request : Count Up from specific time

### ISSUE THREAD

**Issue by whoibrar** [cg2121/obs-advanced-timer#25]
I would like to track the total time spent on something across various recordings visible. 
Would be nice to have an option where I can put in inital value and it would count upwards from there.

**Comment by RomanTruba** [comment]
Hi, I added PR #26, so maybe the author will accept it eventually.
Meanwhile, you can use timer code from my repo https://github.com/RomanTruba/obs-advanced-timer

**Comment by cg2121** [comment]
Added with #9
