### ISSUE TITLE
Not recognizing text source

### ISSUE THREAD

**Issue by jjdeprisco** [cg2121/obs-advanced-timer#7]
OBS 26.0.2, Mac High Sierra

Tried this timer but was unable to select the text source that I set up previously. In fact it's not showing many of my text sources at all. Only four are shown, whereas the standard OBS countdown sees all my text sources and works OK.

**Comment by cg2121** [comment]
Should be fixed with latest commit https://github.com/cg2121/obs-advanced-timer/commit/5db878610b60ef23fe13182f234dfc73eeba203c
